### ISSUE TITLE
Flags of module members

### ISSUE THREAD

**Issue by tineheller** [otris/jsdoc-tsd#44]
1. With `jsdoc` comments it is now possible to mark module members `static` or `inner` (see [myModule2](https://github.com/otris/jsdoc-tsd/blob/master/exampleProject/src/core/myModule2.js)).

2. With `module.export` in `javascript` code it is now possible to mark module members `exported` or `inner` (see [myModule1](https://github.com/otris/jsdoc-tsd/blob/master/exampleProject/src/core/myModule1.js)).

Both, the `static` and the `exported` members will be exported in the generated file.

But for now it is not quite clear why the `@static` tag has to be used in `jsdoc` comments and how the `@exports` tag can be used.

Additional some tests must be added for module member flags.

**Comment by wehrstedt** [comment]
I will close this because its pretty good tested for now. Also, the @static and @inner tags are supported. The @exports tag is used if your module is not an ES 6 module and will be instantiated by an object whose name is not `export`. Then you have to specify the export variable because jsdoc is not able to determine it. But this is nothing we have to handle because it is handled by jsdoc. See https://jsdoc.app/tags-exports.html
